# Generated by Django 4.2.8 on 2025-05-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'tbl_users'},
        ),
    ]
