# Generated by Django 4.2.8 on 2025-05-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profiles/'),
        ),
    ]
