# Generated by Django 4.2.8 on 2025-05-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='type',
            field=models.CharField(choices=[('in', 'Stock-In'), ('out', 'Stock-Out'), ('adjust', 'Adjustment'), ('return', 'Return')], max_length=7),
        ),
    ]
