# Generated by Django 4.2.8 on 2025-05-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_barcode_product_description_product_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile',
            new_name='product_image',
        ),
    ]
